import time
from vllm import LLM, SamplingParams
import torch


# A prompt containing a large markdown table. The table is randomly generated by GPT-4.
LONG_PROMPT = "You are a helpful assistant in recognizes the content of tables in markdown format. Here is a table as follows.\n# Table\n" + """
| ID  | Name          | Age | Occupation    | Country       | Email                  | Phone Number   | Address                       |
|-----|---------------|-----|---------------|---------------|------------------------|----------------|------------------------------|
| 1   | John Doe      | 29  | Engineer      | USA           | john.doe@example.com   | 555-1234       | 123 Elm St, Springfield, IL  |
| 2   | Jane Smith    | 34  | Doctor        | Canada        | jane.smith@example.com | 555-5678       | 456 Oak St, Toronto, ON      |
| 3   | Alice Johnson | 27  | Teacher       | UK            | alice.j@example.com    | 555-8765       | 789 Pine St, London, UK      |
| 4   | Bob Brown     | 45  | Artist        | Australia     | bob.b@example.com      | 555-4321       | 321 Maple St, Sydney, NSW    |
| 5   | Carol White   | 31  | Scientist     | New Zealand   | carol.w@example.com    | 555-6789       | 654 Birch St, Wellington, NZ |
| 6   | Dave Green    | 28  | Lawyer        | Ireland       | dave.g@example.com     | 555-3456       | 987 Cedar St, Dublin, IE     |
| 7   | Emma Black    | 40  | Musician      | USA           | emma.b@example.com     | 555-1111       | 246 Ash St, New York, NY     |
| 8   | Frank Blue    | 37  | Chef          | Canada        | frank.b@example.com    | 555-2222       | 135 Spruce St, Vancouver, BC |
| 9   | Grace Yellow  | 50  | Engineer      | UK            | grace.y@example.com    | 555-3333       | 864 Fir St, Manchester, UK   |
| 10  | Henry Violet  | 32  | Artist        | Australia     | henry.v@example.com    | 555-4444       | 753 Willow St, Melbourne, VIC|
| 11  | Irene Orange  | 26  | Scientist     | New Zealand   | irene.o@example.com    | 555-5555       | 912 Poplar St, Auckland, NZ  |
| 12  | Jack Indigo   | 38  | Teacher       | Ireland       | jack.i@example.com     | 555-6666       | 159 Elm St, Cork, IE         |
| 13  | Karen Red     | 41  | Lawyer        | USA           | karen.r@example.com    | 555-7777       | 357 Cedar St, Boston, MA     |
| 14  | Leo Brown     | 30  | Chef          | Canada        | leo.b@example.com      | 555-8888       | 246 Oak St, Calgary, AB      |
| 15  | Mia Green     | 33  | Musician      | UK            | mia.g@example.com      | 555-9999       | 975 Pine St, Edinburgh, UK   |
| 16  | Noah Yellow   | 29  | Doctor        | Australia     | noah.y@example.com     | 555-0000       | 864 Birch St, Brisbane, QLD  |
| 17  | Olivia Blue   | 35  | Engineer      | New Zealand   | olivia.b@example.com   | 555-1212       | 753 Maple St, Hamilton, NZ   |
| 18  | Peter Black   | 42  | Artist        | Ireland       | peter.b@example.com    | 555-3434       | 912 Fir St, Limerick, IE     |
| 19  | Quinn White   | 28  | Scientist     | USA           | quinn.w@example.com    | 555-5656       | 159 Willow St, Seattle, WA   |
| 20  | Rachel Red    | 31  | Teacher       | Canada        | rachel.r@example.com   | 555-7878       | 357 Poplar St, Ottawa, ON    |
| 21  | Steve Green   | 44  | Lawyer        | UK            | steve.g@example.com    | 555-9090       | 753 Elm St, Birmingham, UK   |
| 22  | Tina Blue     | 36  | Musician      | Australia     | tina.b@example.com     | 555-1213       | 864 Cedar St, Perth, WA      |
| 23  | Umar Black    | 39  | Chef          | New Zealand   | umar.b@example.com     | 555-3435       | 975 Spruce St, Christchurch, NZ|
| 24  | Victor Yellow | 43  | Engineer      | Ireland       | victor.y@example.com   | 555-5657       | 246 Willow St, Galway, IE    |
| 25  | Wendy Orange  | 27  | Artist        | USA           | wendy.o@example.com    | 555-7879       | 135 Elm St, Denver, CO       |
| 26  | Xavier Green  | 34  | Scientist     | Canada        | xavier.g@example.com   | 555-9091       | 357 Oak St, Montreal, QC     |
| 27  | Yara Red      | 41  | Teacher       | UK            | yara.r@example.com     | 555-1214       | 975 Pine St, Leeds, UK       |
| 28  | Zack Blue     | 30  | Lawyer        | Australia     | zack.b@example.com     | 555-3436       | 135 Birch St, Adelaide, SA   |
| 29  | Amy White     | 33  | Musician      | New Zealand   | amy.w@example.com      | 555-5658       | 159 Maple St, Wellington, NZ |
| 30  | Ben Black     | 38  | Chef          | Ireland       | ben.b@example.com      | 555-7870       | 246 Fir St, Waterford, IE    |
"""


def get_generation_time(llm, sampling_params, prompts):
    # time the generation
    start_time = time.time()
    output = llm.generate(prompts, sampling_params=sampling_params)
    end_time = time.time()
    # print the output and generation time
    print(f"Output: {output[0].outputs[0].text}")
    print(f"Generation time: {end_time - start_time} seconds.")
    return end_time - start_time


# set enable_prefix_caching=True to enable APC
llm = LLM(
    model='meta-llama/Llama-3.2-3B',
    #model='lmsys/longchat-7b-16k',
    dtype=torch.bfloat16,
    trust_remote_code=True,
    quantization="bitsandbytes",
    load_format='bitsandbytes',
    enable_prefix_caching=True,
    max_model_len=4096
)

prompt_list = [
"Question: what is the age of John Doe? Your answer: The age of John Doe is ",
"Question: what is the occupation of Jane Smith? Your answer: The occupation of Jane Smith is ",
"Question: what is the age of Zack Blue? Your answer: The age of Zack Blue is ",
"Question: what is the email address of Alice Johnson? Your answer: The email address of Alice Johnson is ",
"Question: what is the phone number of Bob Brown? Your answer: The phone number of Bob Brown is ",
"Question: what country is Carol White from? Your answer: Carol White is from ",
"Question: what is the address of Dave Green? Your answer: The address of Dave Green is ",
"Question: who is 40 years old? Your answer: The person who is 40 years old is ",
"Question: who is the lawyer from Ireland? Your answer: The lawyer from Ireland is ",
"Question: what is the name of the musician from USA? Your answer: The name of the musician from USA is ",
"Question: who has the email frank.b@example.com? Your answer: The person with the email frank.b@example.com is ",
"Question: what is the occupation of the person living on Spruce St, Vancouver? Your answer: The occupation of the person living on Spruce St, Vancouver is ",
"Question: who lives in Wellington, New Zealand? Your answer: The person who lives in Wellington, New Zealand is ",
"Question: what is the occupation of Grace Yellow? Your answer: The occupation of Grace Yellow is ",
"Question: who is 50 years old and from the UK? Your answer: The person who is 50 years old and from the UK is ",
"Question: what is the email of Henry Violet? Your answer: The email of Henry Violet is ",
"Question: who has the occupation of scientist? Your answer: The person with the occupation of scientist is ",
"Question: what is the phone number of Irene Orange? Your answer: The phone number of Irene Orange is ",
"Question: what country is Jack Indigo from? Your answer: Jack Indigo is from ",
"Question: who is 38 years old and a teacher? Your answer: The 38-year-old teacher is ",
"Question: what is the name of the chef from Canada? Your answer: The name of the chef from Canada is ",
"Question: who is the artist residing in Sydney? Your answer: The artist residing in Sydney is ",
"Question: who lives at 753 Willow St, Melbourne? Your answer: The person who lives at 753 Willow St, Melbourne is ",
"Question: who has the occupation of doctor? Your answer: The person with the occupation of doctor is ",
"Question: what is the age of Leo Brown? Your answer: The age of Leo Brown is ",
"Question: who lives in Cork, Ireland? Your answer: The person who lives in Cork, Ireland is ",
"Question: who has the email mia.g@example.com? Your answer: The person with the email mia.g@example.com is ",
"Question: what is the occupation of Noah Yellow? Your answer: The occupation of Noah Yellow is ",
"Question: who is 29 years old and lives in Australia? Your answer: The person who is 29 years old and lives in Australia is ",
"Question: who is a scientist residing in Hamilton? Your answer: The scientist residing in Hamilton is ",
"Question: who is 42 years old and an artist? Your answer: The 42-year-old artist is ",
"Question: what is the email of Quinn White? Your answer: The email of Quinn White is ",
"Question: who is a lawyer from Boston, MA? Your answer: The lawyer from Boston, MA is ",
"Question: what is the occupation of Tina Blue? Your answer: The occupation of Tina Blue is ",
"Question: what is the phone number of Umar Black? Your answer: The phone number of Umar Black is ",
"Question: what is the address of Victor Yellow? Your answer: The address of Victor Yellow is ",
"Question: who lives at 975 Spruce St, Christchurch? Your answer: The person who lives at 975 Spruce St, Christchurch is ",
"Question: what is the age of Wendy Orange? Your answer: The age of Wendy Orange is ",
"Question: who is a chef from Waterford, Ireland? Your answer: The chef from Waterford, Ireland is ",
"Question: what is the email address of Xavier Green? Your answer: The email address of Xavier Green is ",
"Question: who is a musician from UK? Your answer: The musician from UK is ",
"Question: what is the occupation of Ben Black? Your answer: The occupation of Ben Black is ",
"Question: who is the teacher from Leeds, UK? Your answer: The teacher from Leeds, UK is ",
"Question: who has the email address amy.w@example.com? Your answer: The person with the email address amy.w@example.com is ",
"Question: what is the address of the person named John Doe? Your answer: The address of John Doe is ",
"Question: who is the 31-year-old teacher? Your answer: The 31-year-old teacher is ",
"Question: who has the phone number 555-1213? Your answer: The person with the phone number 555-1213 is ",
"Question: what is the address of Steve Green? Your answer: The address of Steve Green is ",
"Question: who is the artist with the email address wendy.o@example.com? Your answer: The artist with the email address wendy.o@example.com is ",
"Question: what is the phone number of Jack Indigo? Your answer: The phone number of Jack Indigo is ",
"Question: who is the chef from Calgary, AB? Your answer: The chef from Calgary, AB is ",
"Question: what is the email of Noah Yellow? Your answer: The email of Noah Yellow is ",
"Question: who has the occupation of musician? Your answer: The person with the occupation of musician is ",
"Question: who is the doctor from Brisbane? Your answer: The doctor from Brisbane is ",
"Question: who is the engineer living on Cedar St, Dublin? Your answer: The engineer living on Cedar St, Dublin is ",
"Question: what is the phone number of Rachel Red? Your answer: The phone number of Rachel Red is ",
"Question: who is the 39-year-old chef? Your answer: The 39-year-old chef is ",
"Question: what is the address of Karen Red? Your answer: The address of Karen Red is ",
"Question: who is 35 years old and an engineer? Your answer: The person who is 35 years old and an engineer is ",
"Question: what is the occupation of Olivia Blue? Your answer: The occupation of Olivia Blue is ",
"Question: who is 50 years old and resides in Manchester? Your answer: The person who is 50 years old and resides in Manchester is ",
"Question: who lives in Ash St, New York, NY? Your answer: The person who lives in Ash St, New York, NY is ",
"Question: who has the occupation of artist in Melbourne, VIC? Your answer: The artist in Melbourne, VIC is ",
"Question: what is the name of the lawyer in Canada? Your answer: The lawyer in Canada is ",
"Question: who is a teacher in Ireland? Your answer: The teacher in Ireland is ",
"Question: what is the name of the engineer in USA? Your answer: The engineer in USA is ",
"Question: who has the email address grace.y@example.com? Your answer: The person with the email address grace.y@example.com is ",
"Question: what is the age of Peter Black? Your answer: The age of Peter Black is ",
"Question: who lives on Maple St in Sydney? Your answer: The person who lives on Maple St in Sydney is ",
"Question: what is the email of Leo Brown? Your answer: The email of Leo Brown is ",
"Question: who is a doctor from Toronto, ON? Your answer: The doctor from Toronto, ON is ",
"Question: who is a lawyer from Seattle, WA? Your answer: The lawyer from Seattle, WA is ",
"Question: who lives in Willow St, Leeds? Your answer: The person who lives in Willow St, Leeds is ",
"Question: who has the email dave.g@example.com? Your answer: The person with the email dave.g@example.com is ",
"Question: what is the occupation of Alice Johnson? Your answer: The occupation of Alice Johnson is ",
"Question: what is the address of Tina Blue? Your answer: The address of Tina Blue is ",
"Question: who is 28 years old and a scientist? Your answer: The 28-year-old scientist is ",
"Question: who is the artist from Denver, CO? Your answer: The artist from Denver, CO is ",
"Question: what is the occupation of Wendy Orange? Your answer: The occupation of Wendy Orange is ",
"Question: what is the phone number of Carol White? Your answer: The phone number of Carol White is ",
"Question: who is the chef living on Spruce St in New Zealand? Your answer: The chef living on Spruce St in New Zealand is ",
"Question: who lives in Poplar St, Auckland? Your answer: The person who lives in Poplar St, Auckland is ",
"Question: who is the engineer in Ireland? Your answer: The engineer in Ireland is ",
"Question: who lives at 357 Oak St in Montreal? Your answer: The person who lives at 357 Oak St in Montreal is ",
"Question: who has the email john.doe@example.com? Your answer: The person with the email john.doe@example.com is ",
"Question: what is the phone number of the scientist from UK? Your answer: The phone number of the scientist from UK is ",
"Question: who is 27 years old and a teacher? Your answer: The 27-year-old teacher is ",
"Question: who is the artist residing on Willow St, Galway? Your answer: The artist residing on Willow St, Galway is ",
"Question: what is the address of Olivia Blue? Your answer: The address of Olivia Blue is ",
"Question: who is the teacher living on Poplar St in Canada? Your answer: The teacher living on Poplar St in Canada is ",
"Question: who is the 44-year-old lawyer? Your answer: The 44-year-old lawyer is ",
"Question: who has the occupation of doctor and lives in Toronto? Your answer: The doctor living in Toronto is ",
"Question: who lives on Elm St in Springfield, IL? Your answer: The person who lives on Elm St in Springfield, IL is ",
"Question: what is the email of the chef in Adelaide? Your answer: The email of the chef in Adelaide is ",
"Question: what is the occupation of Yara Red? Your answer: The occupation of Yara Red is ",
"Question: who is the scientist from Canada? Your answer: The scientist from Canada is ",
"Question: who has the phone number 555-6767? Your answer: The person with the phone number 555-6767 is ",
"Question: who is a musician from Perth, WA? Your answer: The musician from Perth, WA is ",
"Question: what is the occupation of Grace Yellow? Your answer: The occupation of Grace Yellow is ",
"Question: what is the phone number of Leo Brown? Your answer: The phone number of Leo Brown is "]

sampling_params = SamplingParams(temperature=0, max_tokens=100)


total_time = 0


for prompt in prompt_list:
    total_time += get_generation_time(
        llm,
        sampling_params,
        LONG_PROMPT + prompt,
    )

print(f'total time: {total_time}')